fix QueryException not being instantiated properly (#3078)
This happened in the metrics executor logs when the logger tried to print the exception

AttributeError: 'QueryException' object has no attribute 'message'

This is because this exception is not defined properly. This is documented behavior
https://github.com/getsentry/snuba/blob/master/snuba/utils/serializable_exception.py#L90-L94

This will also most likely fix the double raising of exceptions issues in sentry