ref(ci): Fix up a bunch of flaky tests (#5292)
* ref(ci): Fix up assertion to be more verbose

We are experiencing CI flakes like this:

Traceback (most recent call last):
  File "/usr/src/snuba/tests/clickhouse/optimize/test_optimize_tracker.py", line 282, in test_run_optimize_with_ongoing_merges
    sleep_mock.assert_called_with(settings.OPTIMIZE_BASE_SLEEP_TIME)
  File "/usr/local/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: sleep(300)
Actual: sleep(5)

However, the failing assertion itself is a duplicate of the assertion
below it. Removing this one will make the test fail at the next one
using call_args_list, which gives us more information about the flake

* add debug assert for another flaky test

* ignore flaky test entirely

* disable profiler in tests