feat(job-runner): persist logs in Redis for easier viewing in snuba admin (#6387)
This PR creates a new JobLogger interface that writes logs to standard
handlers as normal but also pushes them to a Redis list.

Some unrelated changes to simplify this and testing:
1. added a new module named `redis` inside job_runner so that both
`logging` and `runner` could refer to it. This required moving JobStatus
out of runner
2. changed `ToyJob` to allow simulation of a failure based on parameters

Next step: load this data from snuba admin so that users can see logs
after a job has run/failed without going to the FS/GCP.

Example runs:
```
➜  snuba git:(job-runner/multiplex-logs) ✗ snuba jobs run --job_id=1234567890123456789 --job_type=ToyJob fail=1
2024-10-04 09:18:15,533 Initializing Snuba...
2024-10-04 09:18:17,149 Snuba initialization took 1.6182118870056001s
2024-10-04 09:18:17,172 executing job 1234567890123456789 with query `query`
2024-10-04 09:18:17,176 Job execution failed
2024-10-04 09:18:17,182 exception Traceback (most recent call last):
  File "/Users/oliver/workplace/snuba/snuba/manual_jobs/runner.py", line 113, in run_job
    job_to_run.execute(job_logger)
  File "/Users/oliver/workplace/snuba/snuba/manual_jobs/toy_job.py", line 29, in execute
    raise Exception("failed as requested")
Exception: failed as requested

resulting job status = failed

➜  snuba git:(job-runner/multiplex-logs) ✗ snuba jobs view-logs --job_id=1234567890123456789
2024-10-04 09:18:23,347 Initializing Snuba...
2024-10-04 09:18:25,009 Snuba initialization took 1.6640102680103155s
start redis logs
[INFO] Fri Oct  4 09:18:17 2024: executing job 1234567890123456789 with query `query`
[ERROR] Fri Oct  4 09:18:17 2024: Job execution failed
[INFO] Fri Oct  4 09:18:17 2024: exception Traceback (most recent call last):
  File "/Users/oliver/workplace/snuba/snuba/manual_jobs/runner.py", line 113, in run_job
    job_to_run.execute(job_logger)
  File "/Users/oliver/workplace/snuba/snuba/manual_jobs/toy_job.py", line 29, in execute
    raise Exception("failed as requested")
Exception: failed as requested

end redis logs
```

```
➜  snuba git:(job-runner/multiplex-logs) ✗ snuba jobs run --job_id=12345678901 --job_type=ToyJob
2024-10-04 08:01:17,166 Initializing Snuba...
2024-10-04 08:01:18,768 Snuba initialization took 1.6043320349999703s
2024-10-04 08:01:18,791 executing job 12345678901 with query `query`
2024-10-04 08:01:18,795 Job execute finished
resulting job status = finished

➜  snuba git:(job-runner/multiplex-logs) ✗ snuba jobs view-logs --job_id=12345678901
2024-10-04 08:01:22,408 Initializing Snuba...
2024-10-04 08:01:24,032 Snuba initialization took 1.6255243710038485s
start redis logs
[INFO] Fri Oct  4 08:01:18 2024: executing job 12345678901 with query `query`
[INFO] Fri Oct  4 08:01:18 2024: Job execute finished
end redis logs
```