fix(inc-1013): account for explicitly None fields in contexts (#6823)
In the logs of the consumer:

```
 if profile.get("profile_id") is not None:
^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

This means that the profile value was explicitly set to None in the
payload. make the context handling account for that case