feat(config): check value types (#2187)
The current config system does not check the type of the values being set
for keys. This allows for user mistakes where the type of the value could
be changed unknowingly. Added type checking for values and an option to
override it in case the existing value type was incorrectly set.

### Tests
Tests using CLI which is the primary method of setting configs today

```
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc 1                                                                                       ok | direnv  3.8.11 py  10:33:39 AM
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc 2                                                                                       ok | direnv  3.8.11 py  10:40:51 AM
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc 0.5                                                                                     ok | direnv  3.8.11 py  10:41:00 AM
Mismatched types for abc: Original type: <class 'int'>, New type: <class 'float'>
Traceback (most recent call last):
  File "/Users/nikharsaxena/workspace/snuba/snuba/state/__init__.py", line 131, in set_config
    raise MismatchedTypeException(key, type(original_value), type(value))
snuba.state.MismatchedTypeException: ('abc', <class 'int'>, <class 'float'>)
The new value type <class 'float'> does not match the old value type <class 'int'>. Use the force option to disable this check
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc 0.5 --force                                                                             ok | direnv  3.8.11 py  10:41:20 AM
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc some-string                                                                             ok | direnv  3.8.11 py  10:41:32 AM
Mismatched types for abc: Original type: <class 'float'>, New type: <class 'str'>
Traceback (most recent call last):
  File "/Users/nikharsaxena/workspace/snuba/snuba/state/__init__.py", line 131, in set_config
    raise MismatchedTypeException(key, type(original_value), type(value))
snuba.state.MismatchedTypeException: ('abc', <class 'float'>, <class 'str'>)
The new value type <class 'str'> does not match the old value type <class 'float'>. Use the force option to disable this check
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config set abc some-string --force                                                                     ok | direnv  3.8.11 py  10:41:46 AM
 ~/workspace/snuba  nikhar/type-check-values *8 ?2  snuba config get-all                                                                                         ok | direnv  3.8.11 py  10:41:53 AM
test-float = 0.5 (float)
test-str = 'some-string' (str)
abc = 'some-string' (str)
```